idf_component_register(SRCS "sntp.c" "app_main.c"
                            "../../../third_party/vscp-firmware/common/vscp-firmware-helper.c"
                            "../../../third_party/vscp-firmware/common/vscp-link-protocol.c"
                            "../../../third_party/vscp-firmware/common/crc.c"
                            "../../../third_party/vscp-firmware/common/vscp-aes.c"
                            "../../../third_party/vscp-firmware/common/vscp-fifo.c"
                            "dllist.c"
                            "vscp_led_indicator_blink.c"
                            "callbacks-vscp-protocol.c"
                            "urldecode.c"
                            "mqtt.c"
                            "websrv.c"
                            "callbacks-link.c"
                            "tcpsrv.c"
                            "udp_logging.c"
                            "vscp-espnow.c"
                            "sntp.c"
                          INCLUDE_DIRS "."
                            "../../../third_party/vscp-firmware/common/"
                            "../../../third_party/vscp/src/vscp/common"
                            "../../../")
