name: Build Beta ESP32

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
  
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32
        path: './firmware/beta/'
    
    - uses: actions/upload-artifact@v3
      with:
        name: vscp_espnow_beta.bin
        path: ./firmware/beta/build/vscp_espnow_beta.bin
        retention-days: 7