name: Build Alpha ESP32

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VSCP_FIRMWARE: ./vscp-firmware/
  VSCP_FIRMWARE_COMMON: ./vscp-firmware/common/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set environment variables       
      run: |
        echo "VSCP_FIRMWARE=./vscp-firmware/" >> $GITHUB_ENV
        echo "VSCP_FIRMWARE_COMMON=./vscp-firmware/common/" >> $GITHUB_ENV
    
    - name: test
      run: echo $VSCP_FIRMWARE

    - name: Update before installing packages
      run: sudo apt-get update
      
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0
        target: esp32
        path: './firmware/alpha/'
    