name: Build Alpha ESP32

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Checkout vscp-firmware
      run: git clone https://github.com/grodansparadis/vscp-firmware.git

    - name: export path
      run: |
        export VSCP_FIRMWARE=./vscp-firmware/
        export VSCP_FIRMWARE_COMMON=./vscp-firmware/common/  

    - name: Update before installing packages
      run: sudo apt-get update
      
    - name: Install pandoc manually
      run: sudo apt-get install pandoc

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0
        target: esp32
        path: 'firmware/alpha'
    